### PR TITLE
Separeted and character dependent voices

### PR DESCRIPTION
**Pull request by TomyGamy**
Allow the voice to be change depending on the played character, also separated voices to make the opponent not stop singing when the player miss (examples on the test song)

### CODE REVIEW

**Comment by lunarcleint** [comment]
you can add this in hscript bro...,,,..

**Comment by TomyGamy** [comment]
On the Charting state? (WIP)
This is very useful in this tool

**Comment by biomseed** [comment]
this is how the base game update will handle it actually

**Comment by lunarcleint** [comment]
you can add it in charting with hscript

**Pull request closed without merging**
