### PR TITLE
Iphone NDLL support (woah)

### PR DESCRIPTION
**Pull request by mcagabe19**
man why *crying*

### CODE REVIEW

**Comment by NeeEoo** [comment]
Does these platforms actually support ndll?
And why iphonesim?

**Comment by mcagabe19** [comment]
[it does](https://github.com/openfl/lime/blob/4ed893afbd3a9b16990b530fd3fcaca679fb6d12/.github/workflows/main.yml#L342-L402)

**Comment by NeeEoo** [comment]
I dont see iphonesim on the link you sent

**Comment by mcagabe19** [comment]
`-simulator`

**Comment by NeeEoo** [comment]
Im not sure if i want iphonesim since like its called an iPhone simulator, wouldnt it be able to simulate ios ndlls too???

**Comment by mcagabe19** [comment]
it's due mostly simulators are used in mac and... some macs are x86_64

**Comment by NeeEoo** [comment]
Ohhh so its a toggle between intel and arch?
Still kinda feels dumb that there's 2 different iphone tags

**Comment by mcagabe19** [comment]
if you want remove iphonesim do it but keep ios atleast cuz lime build ios does not work at codename engine due that

**Comment by NeeEoo** [comment]
Also dont forget to edit the project.xml

**Comment by mcagabe19** [comment]
check our mobile repo I doing just pull this or close this

**Comment by NeeEoo** [comment]
No like i mean edit project.xml to add the conditional to NDLL_SUPPORTED

**Pull request merged**
