### PR TITLE
Add extra charter controls

### PR DESCRIPTION
**Pull request by bctix**
Adds quality of life controls to the charter.

Additions/changes:
- Youtube hotkeys (without shift) for playback speed (< and >)
- Go to start of section (Shift + S)
- Go forward and back a step (W and S)

image

### CODE REVIEW

**Comment by PetscopF** [comment]
I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.

**Comment by bctix** [comment]
> I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.

There are still no "sections" in the editor/chart. The snap to start of section is really just to snap to the start of the measure. It's just named section for consistancy with the other controls. If the devs want to keep it as section, or change it to measure is up to them.

**Comment by PetscopF** [comment]
> > I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.
> 
> There are still no "sections" in the editor/chart. The snap to start of section is really just to snap to the start of the measure. It's just named section for consistancy with the other controls. If the devs want to keep it as section, or change it to measure is up to them.

Ah, alright then. Thanks for the clarification.

**Review by rodney528 — APPROVED** [review]

**Comment by NexIsDumb** [comment]
> I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.

well there is a concept of section, for example look at the public cne build
image

and u can also visually see a section in the charter by looking at the thickness of lines
image

and btw im avluing to merge this, im asking thoughts to the others first

**Comment by PetscopF** [comment]
> > I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.
> 
> well there is a concept of section, for example look at the public cne build image
> 
> and u can also visually see a section in the charter by looking at the thickness of lines image

Ah, alright. I just usually associated sections similarly to how Psych does (particularly with its cameras), since I tend to code and chart in Psych for some mods while using Codename for the rest.

**Review by rodney528 — APPROVED** [review]

**Comment by NexIsDumb** [comment]
> > > I'm a little unsure why you would need the sections functionality, considering the fact that Codename Engine lacks such a concept. It feels a little misleading to me, especially with how Codename replaces the idea with simple camera switches that are very customizable in how they work.
> > 
> > well there is a concept of section, for example look at the public cne build image
> > 
> > and u can also visually see a section in the charter by looking at the thickness of lines image
> 
> Ah, alright. I just usually associated sections similarly to how Psych does (particularly with its cameras), since I tend to code and chart in Psych for some mods while using Codename for the rest.

fair fair

**Comment by NexIsDumb** [comment]
fun thingie i noticed: if u spam comma or period it goes beyond the slider's max and min values, lemme fix

**Comment by rodney528** [comment]
lol

**Pull request merged**
