### PR TITLE
Temporary mute fix

### PR DESCRIPTION
**Pull request by MemeHovy**
I fucking hate that bullshit default keybind being numpad 0
so I made this temporary fix

### CODE REVIEW

**Comment by BombasticTom** [comment]
why didn't you just add a control for volume keys then??

**Comment by biomseed** [comment]
> why didn't you just add a control for volume keys then??

that already exists, press + and -

**Comment by MemeHovy** [comment]
> why didn't you just add a control for volume keys then??

fair

**Comment by MemeHovy** [comment]
> > why didn't you just add a control for volume keys then??
> 
> that already exists, press + and -

I think he means make them customizable keybinds (which I might do)

**Comment by BombasticTom** [comment]
> > > why didn't you just add a control for volume keys then??
> > 
> > 
> > that already exists, press + and -
> 
> I think he means make them customizable keybinds (which I might do)

this

**Comment by lunarcleint** [comment]
3 months old, prob finna mess with the chart editor

**Comment by MemeHovy** [comment]
> 3 months old, prob finna mess with the chart editor

alright

**Pull request closed without merging**
