### PR TITLE
Made update file shell executable for linux

### PR DESCRIPTION
**Pull request by TumoPlayz**
you may not see anything but now people can run "./update.sh" and it will run

### CODE REVIEW

**Comment by TumoPlayz** [comment]
this aged like milk

**Comment by TumoPlayz** [comment]
re opened because read me is misleading

**Comment by TumoPlayz** [comment]
the folder for common commands is /bin/bash not /bin/sh

**Comment by lunarcleint** [comment]
alreadly added

**Comment by TumoPlayz** [comment]
OH

**Pull request closed without merging**
