### PR TITLE
macarao

### PR DESCRIPTION
**Pull request by Gazozoz**
salxixa

### CODE REVIEW

**Review by BeastlyGabi — APPROVED** [review]

**Review by MemeHovy — APPROVED** [review]
https://github.com/FNF-CNE-Devs/CodenameEngine/assets/124418090/7d350be9-6b59-4dda-ba31-25a8a3caf9a6

**Review by swordcube — APPROVED** [review]

**Comment by MemeHovy** [comment]
> even if its useless i find it funny

true

**Comment by lunarcleint** [comment]
macarao

**Comment by enderpuff** [comment]
macarao com salxixa

**Pull request closed without merging**
