### PR TITLE
fix an incorrect verb in README.md

### PR DESCRIPTION
**Pull request by bambamlolol**

### CODE REVIEW

**Review by MemeHovy — CHANGES_REQUESTED** [review]
this is more of a incorrect auxiliary as Charles said, not a spelling mistake

**Comment by bambamlolol** [comment]
> this is more of a incorrect auxiliary as Charles said, not a spelling mistake

whoops

**Comment by CharlesCatYT** [comment]
this isnt needed anymore now that this change was already done recently

you can just close it now

**Comment by lunarcleint** [comment]
😭

**Comment by bambamlolol** [comment]
> this isnt needed anymore now that this change was already done recently
> 
> you can just close it now

alright

**Pull request closed without merging**
