### PR TITLE
Make offset points get put in the pool when FunkinSprite is destroyed

### PR DESCRIPTION
**Pull request by MemeHovy**
thanks to @Sword352 for the assist

### CODE REVIEW

**Comment by MemeHovy** [comment]
> slay

ikr

**Review by Sword352 — APPROVED** [review]
SLAAAAY

**Comment by MemeHovy** [comment]
> SLAAAAY

🥰

**Comment by NeeEoo** [comment]
Add a null check on the animOffsets in destroy, just to prevent a crash if you destroy it twice

**Comment by MemeHovy** [comment]
> Add a null check on the animOffsets in destroy, just to prevent a crash if you destroy it twice

alright 👍🏻

**Pull request merged**
