### PR TITLE
allow me to use my mouse scroll wheel in the mod menu

### PR DESCRIPTION
**Pull request by usb-port-2**
please i have like 70 mod folders i dont want to press down 50 times to find a mod

### CODE REVIEW

**Review by mcagabe19 — APPROVED** [review]

**Review by charlesisfeline — APPROVED** [review]

**Comment by NexIsDumb** [comment]
doneeee

**Comment by usb-port-2** [comment]
TYSM ILY

**Comment by NexIsDumb** [comment]
oh wait i forgor pixel pause holon

**Comment by usb-port-2** [comment]
𝓶𝓮𝓻𝓰𝓮 𝓲𝓽 𝓹𝓵𝓼

**Comment by usb-port-2** [comment]
oh ok

**Comment by NexIsDumb** [comment]
> 𝓶𝓮𝓻𝓰𝓮 𝓲𝓽 𝓹𝓵𝓼

𝓱𝓸𝓵𝓭 𝓸𝓷

**Comment by usb-port-2** [comment]
> > 𝓶𝓮𝓻𝓰𝓮 𝓲𝓽 𝓹𝓵𝓼
> 
> 𝓱𝓸𝓵𝓭 𝓸𝓷

𝓸𝓴 𝓽𝓱𝓪𝓷𝓴 𝔂𝓸𝓾 𝓯𝓸𝓻 𝓽𝓪𝓴𝓲𝓷𝓰 𝓽𝓱𝓮 𝓽𝓲𝓶𝓮 𝓸𝓾𝓽 𝓸𝓯 𝔂𝓸𝓾𝓻 𝓭𝓪𝔂 𝓽𝓸 𝔀𝓸𝓻𝓴 𝓸𝓷 𝓽𝓱𝓲𝓼

**Comment by mcagabe19** [comment]
freaky people

**Comment by NexIsDumb** [comment]
> freaky people

𝔂𝓮𝓼

**Comment by PetscopF** [comment]
> freaky people

true

**Pull request merged**
