### PR TITLE
Added Sprite linking to FunkinSprite.hx

### PR DESCRIPTION
**Pull request by jasontheone111**
I coded in a way to link FunkinSprites together.
Can be used to link 2 sprite-sheets together. <- The main reason I coded this in.

:D

Usage Example:

- Create two sprites, each with different animations.
- Link sprite two to sprite one (sprite1.addLinkedSprite(sprite2, true);)
- Play anim on sprite one
- Anim does not exist in sprite one, but does exist on linked sprite (sprite two)
- Anim plays on linked sprite (Can hide parent sprite if chosen, on by default)
- Yipeee.

### CODE REVIEW

**Review by RodneyAnImaginativePerson — APPROVED** [review]
Very interesting. But why not instead of setting the alpha on playAnim to set it in the draw function or smth?

**Comment by jasontheone111** [comment]
> Very interesting. But why not instead of setting the alpha on playAnim to set it in the draw function or smth?

Simpler

**Comment by jasontheone111** [comment]
Don't pull this one, I thing I screwed something up, lemme recode it.

**Comment by jasontheone111** [comment]
Made new vesrion

**Pull request closed without merging**
