### PR TITLE
put substate scripts in their own folder

### PR DESCRIPTION
**Pull request by swordcube**
it's annoying to have states and substates in the same exact folder

### CODE REVIEW

**Comment by swordcube** [comment]
literally a 3 letter fix

**Comment by RafGamign** [comment]
g 🌮

**Comment by Stilic** [comment]
bad idea since it can break existing scripts
people will never guess the problem bruh

**Comment by swordcube** [comment]
> bad idea since it can break existing scripts people will never guess the problem it causes at the end bruh

i could also make the change backwards compatible

**Comment by lunarcleint** [comment]
substates and states are un-separated in source so why should they be here?

**Pull request closed without merging**
