### PR TITLE
COLORS BABY

### PR DESCRIPTION
**Pull request by RodneyAnImaginativePerson**
Now when the option is on they will actually have colored health bars!

### CODE REVIEW

**Comment by NexIsDumb** [comment]
oh for this you gotta ask @NeeEoo
i also had the same idea but when I asked him, he said they wanted to keep the og fnf vibes

**Comment by NexIsDumb** [comment]
okay they just changed idea😭

**Comment by RodneyAnImaginativePerson** [comment]
> oh for this you gotta ask @NeeEoo i also had the same idea but when I asked him, he said they wanted to keep the og fnf vibes

there is literally an option in settings for this

**Comment by NexIsDumb** [comment]
> > oh for this you gotta ask @NeeEoo i also had the same idea but when I asked him, he said they wanted to keep the og fnf vibes
> 
> 
> 
> there is literally an option in settings for this

ik but again ask neeo not me, he told me to not to😭

**Pull request merged**
