### PR TITLE
Made main menu shows the current keybind key for opening mods select menu

### PR DESCRIPTION
**Pull request by KarimAkra**

### CODE REVIEW

**Review by RodneyAnImaginativePerson — APPROVED** [review]

**Review by swordcube — APPROVED** [review]

**Review by moxie-coder — APPROVED** [review]

**Comment by NexIsDumb** [comment]
ty!!

**Comment by NexIsDumb** [comment]
oops although you made a smoll typo in the code, lemme fix it rq

**Comment by NexIsDumb** [comment]
alr now fr ty!!

**Comment by KarimAkra** [comment]
yw didn't notice that typo XD

**Pull request merged**
