### PR TITLE
Add bold numbers to alphabet

### PR DESCRIPTION
**Pull request by D-electra**

### CODE REVIEW

**Comment by KadePleaseHelpMe** [comment]
is there an image file to go with this or am I allowed to make it

**Comment by KadePleaseHelpMe** [comment]
nevermind I just checked and it's already in the files
@lunarcleint what the hell why haven't you finished this yet

**Comment by D-electra** [comment]
> w alphabet-bold

you can push it to [this fork](https://github.com/D-electra/CodenameEngine)

**Comment by KadePleaseHelpMe** [comment]
this has been an epic
I'm making the period next

**Comment by D-electra** [comment]
> this has been an epic I'm making the period next

Man, you can do whatever you want to do first, and then make a pull request

**Comment by D-electra** [comment]
> no need to make the dot, we already have that in dev, nor the '

oh, okay

**Comment by D-electra** [comment]
> no need to make the dot, we already have that in dev, nor the '

I've removed all the extra characters

**Comment by KadePleaseHelpMe** [comment]
well... shit ok

**Comment by D-electra** [comment]
ok' i think it's useless pr

**Pull request closed without merging**
