### PR TITLE
!! IMPORTANT CHANGES !!

### PR DESCRIPTION
**Pull request by usb-port-2**

### CODE REVIEW

**Comment by 2Schoolhouse** [comment]
VERY important changes,.

**Comment by CharlesCatYT** [comment]
thank you for getting me to notice, i promised not to miss out on this,,,,,,,,,,,,,,,,,

**Review by 2Schoolhouse — APPROVED** [review]

**Comment by usb-port-2** [comment]
the engine would die without these crucial changes

**Comment by NexIsDumb** [comment]
😭

**Comment by usb-port-2** [comment]
> 😭

PLEASE NEX I NEED THESE CHNAGES NOW GRAHHH

:33

**Comment by usb-port-2** [comment]
Okii

**Pull request merged**
