### PR TITLE
Adjusted menus

### PR DESCRIPTION
**Pull request by NexIsDumb**
This pr is for fixing/cleaning/optimize a bit of stuff in the menus
It's gonna stay as draft until im done with doing

Related to spritesheets stuff: no I didn't use animate, I did it all manually LOL

### CODE REVIEW

**Comment by NexIsDumb** [comment]
Fixed Main Menus Spirtes offsets (NOw they wont move anymore)
Made the Title Enter spritesheet better cleaned
Fixed Coop text in freeplay (Now the dark text background will resize based on it): https://streamable.com/5gd1js
Restored Credits Menu (Will download data directly from Github): https://streamable.com/3n8qkg

**Comment by NexIsDumb** [comment]
In the future I might upload more changes to the credits menu

**Review by MemeHovy — APPROVED** [review]

**Comment by lunarcleint** [comment]
W commit fr

**Comment by NexIsDumb** [comment]
Hehe

**Comment by MemeHovy** [comment]
> W commit fr

agreed

**Pull request merged**
