### PR TITLE
Very minor change but...

### PR DESCRIPTION
**Pull request by SrtHero278**
Can you merge this so scripts in `assets/data/charts/` apply in every song?
It's annoying since I have some global scripts that I wanna to be able to use in mods.
Not to mention that with how it is currently, you have to put a script in every mod if you want to use a fanmade editor.

### CODE REVIEW

**Comment by BushTrain460615** [comment]
what about people who want to use charts on specific songs?

**Comment by SrtHero278** [comment]
> what about people who want to use charts on specific songs?

This is for PlayState global scripts. Song specific scripts are in `songs/[SONG-NAME]/scripts`.

**Comment by BushTrain460615** [comment]
ok my mistake

**Comment by lunarcleint** [comment]
Already added in

**Pull request closed without merging**
