### PR TITLE
added "-loop" stuff

### PR DESCRIPTION
**Pull request by RodneyAnImaginativePerson**

### CODE REVIEW

**Review by CharlesCatYT — APPROVED** [review]
probably should make use of this like add in the loop anims for daddy dearest, bf-car, gf-car(?), and mom-car but ok

**Comment by RodneyAnImaginativePerson** [comment]
> probably should make use of this like add in the loop anims for daddy dearest, bf-car, gf-car(?), and mom-car but ok

Yeah I probably should've add the anims lol

**Comment by CharlesCatYT** [comment]
what about dearest

**Comment by RodneyAnImaginativePerson** [comment]
> what about dearest

What??

**Comment by RodneyAnImaginativePerson** [comment]
Wdym? He never had loop anims.

**Comment by CharlesCatYT** [comment]
oh

**Comment by RodneyAnImaginativePerson** [comment]
> oh

I just doubled check psych's dad json, I might do it

**Comment by CharlesCatYT** [comment]
may probably also involve updating the spritesheet if required but yeah good luck

**Comment by RodneyAnImaginativePerson** [comment]
> may probably also involve updating the spritesheet if required but yeah good luck

it doesn't, the anims are long enough

**Comment by RodneyAnImaginativePerson** [comment]
I just realized I never did "da".

**Comment by RodneyAnImaginativePerson** [comment]
now I have

**Comment by NexIsDumb** [comment]
okay i think you might wanna wait for the full update to come out cuz i did smth similar for this

**Comment by NexIsDumb** [comment]
i think its time to value this pr
cause i have to remake the update branch in dev that had smth similar to this, but at this point; lemme look at this

**Comment by NexIsDumb** [comment]
there we go! thanks!!

**Pull request merged**
