### PR TITLE
Added Color attribute to stage sprites

### PR DESCRIPTION
**Pull request by usb-port-2**

### CODE REVIEW

**Comment by Frakits** [comment]
that attribute already exists...
image

https://github.com/FNF-CNE-Devs/CodenameEngine/blob/2be2c68c9b9268df7c7f9dc0a445f8890ce98992/source/funkin/backend/utils/XMLUtil.hx#L154

**Comment by usb-port-2** [comment]
i may be stupid FUCK

what format does the color need to be in

**Comment by Frakits** [comment]
> i may be stupid FUCK
> 
> what format does the color need to be in

image

**Comment by usb-port-2** [comment]
oh ty

**Pull request closed without merging**
