### PR TITLE
Add array option type

### PR DESCRIPTION
**Pull request by bctix**
adds an array option type :)

https://github.com/FNF-CNE-Devs/CodenameEngine/assets/51544115/5454da64-c460-40d6-afba-b3ea8815eb68

### CODE REVIEW

**Comment by lunarcleint** [comment]
This is a REALLY nice pull request, we've been meaning to add this for awhile. Just can you explain why you chose to use the inner data of the xml attributes instead of using the original data structure? It clashes with the rest of the xml

**Comment by bctix** [comment]
> This is a REALLY nice pull request, we've been meaning to add this for awhile. Just can you explain why you chose to use the inner data of the xml attributes instead of using the original data structure? It clashes with the rest of the xml

Ne_Eo asked me to structure the xml like that.

**Comment by lunarcleint** [comment]
Me and Ne_Eo talked about it and if you change it back we will merge you pull request :D, sorry for the time loss 😭

**Comment by lunarcleint** [comment]
thank you for cool pull :D

**Pull request merged**
