### PR TITLE
Added optional Extra Data support to ModState/ModSubState

### PR DESCRIPTION
**Pull request by Nikorasu-d**
## First
I dont know if this is already implemented :P, feel free to reject this if i'm wrong, feel free to comment

## What i've added?

This adds support to ModStates and ModSubstates to access entry data from a previous state

## Use Case

You will use this if you have a hub state that switchState to a handler that loads assets based on incomming data, for example:

#### WorldSelectionState.hx :
- Here you will manage the user selection and then redirect to a world
- Based on Selection you will have a switch case clausule that is going to load WorldState.hx based on user selection
- Then you will do this in any case:

```haxe 
case 0:
        FlxG.switchState(new ModState('WorldState',{
                 'worldID': 0 
        })); // This will say to state to load assets based on this.data.worldID
```

#### WorldState.hx:

- Here you will have access to the data and then you going to use it like this:

```haxe 

function create(){
	loadAssets();
}

function loadAssets(){
	trace('loading assets of World' + this.data.worldID);
}
```

## Which kind of data you can pass to this.data:

```haxe 

FlxG.switchState(new ModState('substates/tutorialSubstate',{
                'indices' : [1,2,3,4,5],
                'State' : this, //Actual State
                'function': function(){
                    trace('poto');
                },
                'String': 'HelloWorld',
                'Int': 0,
                'Float': .1,
                ... 
            }));
```

You can pass all kind of data :D, including functions, you just need to be creative

## Why you need to accept this?

Why not? jk 🅰️ XD

This allows coders to create reusable code. 
I've been working with this on my projects and it is very helpful to have fast access to data from a previous state.

### CODE REVIEW

**Comment by NexIsDumb** [comment]
oh! this looks good, but imo you should change the argument names from jsonData to data too since it can allow any kind of data (classes included for example) and also you should remove the null checks cause if the coder wants it to set it as null on pirpose and the check its still on, it can get the even previous one data (since it wont set it if the if its null because of that if condition)

**Comment by NeeEoo** [comment]
Nevermind about the nullcheck

**Comment by NexIsDumb** [comment]
nvm we had a better idea, thanks tho!

**Comment by NeeEoo** [comment]
Could you please review the changes i pushed, and see if you are okay with them?

**Review by Nikorasu-d — COMMENTED** [review]
Thats good, i think it is better written xd

**Comment by NeeEoo** [comment]
Please use 

```
/**
 * message here
**/
public static...
```

this means it will show up in the documentation

**Comment by Nikorasu-d** [comment]
> > Please use
> > ```
> > /**
> >  * message here
> > **/
> > public static...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this means it will show up in the documentation
> 
> in this way we can make the message display when hovering over the variable (in vsc for example) or in the API documentation of the engine

sure

**Comment by Nikorasu-d** [comment]
> > Please use
> > ```
> > /**
> >  * message here
> > **/
> > public static...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this means it will show up in the documentation
> 
> in this way we can make the message display when hovering over the variable (in vsc for example) or in the API documentation of the engine

There it is, gonna appreciate a comment 👋

**Comment by Nikorasu-d** [comment]
i've test this on a build and is a little bit buggy, so i delete the null setter, because the class already has a null for data, is not necessary

**Review by NeeEoo — CHANGES_REQUESTED** [review]
Undo this, this has a usage to reset the stored data if the state name changes

**Review by Nikorasu-d — COMMENTED** [review]
Think there was a problem with my specific code, gonna undo the change, sorry 🫂

**Comment by NexIsDumb** [comment]
lemme test it rq and then i think we can merge :p

**Comment by NexIsDumb** [comment]
lemme push some changes rq requested by Neeo

**Comment by NexIsDumb** [comment]
image

yay

**Comment by NexIsDumb** [comment]
and with the lastest 2 commits you can now access the vars like this in the modded state @Nikorasu-d 

image

**Comment by Nikorasu-d** [comment]
> and with the lastest 2 commits you can now access the vars like this in the modded state @Nikorasu-d
> 
> image
> 
> thanks!

oh the last thing is helpful

> and with the lastest 2 commits you can now access the vars like this in the modded state @Nikorasu-d
> 
> image
> 
> thanks!
oh thanks for merging this, i'm gonna try the last thing looks good

**Pull request merged**
