### PR TITLE
Add alter exclusions to HudCamera

### PR DESCRIPTION
**Pull request by D-electra**
This will avoid having to create a new camera to add custom objects to the HUD

### CODE REVIEW

**Comment by NeeEoo** [comment]
To be honest i would add a field to flxsprite so its more optimized, but thats not possible yet :/ since we have the macro on the dev repo, unless we push the macro to the public repo @NexIsDumb

**Comment by NexIsDumb** [comment]
> To be honest i would add a field to flxsprite so its more optimized, but thats not possible yet :/ since we have the macro on the dev repo, unless we push the macro to the public repo @NexIsDumb 

eh.. we just gotta wait for lunar to finish what he wanted so we can publish

**Comment by usb-port-2** [comment]
> > To be honest i would add a field to flxsprite so its more optimized, but thats not possible yet :/ since we have the macro on the dev repo, unless we push the macro to the public repo @NexIsDumb
> 
> eh.. we just gotta wait for lunar to finish what he wanted so we can publish

this is never being added 💔

**Comment by NexIsDumb** [comment]
> > > To be honest i would add a field to flxsprite so its more optimized, but thats not possible yet :/ since we have the macro on the dev repo, unless we push the macro to the public repo @NexIsDumb
> > 
> > eh.. we just gotta wait for lunar to finish what he wanted so we can publish
> 
> this is never being added 💔 

just wait smh

**Comment by NexIsDumb** [comment]
wha why did you close

**Comment by D-electra** [comment]
> wha why did you close just wait a little bit

I'll open this request later when you can pull it, now I've made another one

**Pull request closed without merging**
