### PR TITLE
Base folder asset scanning (because no mod support breaks freeplay)

### PR DESCRIPTION
**Pull request by sillycodergirl**
So on a mod, we removed mod support from the project.xml file, and caused a few bugs, mainly freeplay which is what I added and fixed here!

Pretty simple fix using haxe's FileSystem!

### CODE REVIEW

**Comment by NexIsDumb** [comment]
this looks very fine imo :D 
altho I have to warn ya that in the new update (that will come out in a short time) this class has been edited a lot, so you might wanna edit again this pull request once the update is out

**Comment by NexIsDumb** [comment]
tyy!!

**Comment by NexIsDumb** [comment]
uh oh hold on seems you forgot the cne test part, imma fix rq

**Comment by NexIsDumb** [comment]
oh wiat no, now that i see it the whole pr is bugged, i'll check it out better

**Comment by NexIsDumb** [comment]
im sorry but this is causing many bugs, im forced to remove the commit

**Comment by sillycodergirl** [comment]
> im sorry but this is causing many bugs, im forced to remove the commit

aw that sucks whats bugged ill see if i can fix it rq

**Pull request merged**
