### PR TITLE
Asset optimization

### PR DESCRIPTION
**Pull request by CobaltBar**
`oxipng -o 6 --strip safe --alpha -r art`
`oxipng -o 6 --strip safe --alpha -r assets`

why?
i got bored

### CODE REVIEW

**Comment by NeeEoo** [comment]
Theres a lot of files with only like -20 bytes, also have u made sure that none of the quality is lost?
[image-hash.py](https://github.com/user-attachments/files/16738223/image-hash.py.txt)

**Comment by NeeEoo** [comment]
wait please excuse me the script is a bit broken i forgot to account for alpha

**Comment by NeeEoo** [comment]
[image-hash.py.txt](https://github.com/user-attachments/files/16738234/image-hash.py.txt)
Here please use this

**Comment by NeeEoo** [comment]
[image-hash.py.txt](https://github.com/user-attachments/files/16738236/image-hash.py.txt)
Here please use this

**Comment by CobaltBar** [comment]
i modified it to be recursive

i'll send the output once its finished

**Comment by NeeEoo** [comment]
May i see the code?

**Pull request merged**
