### PR TITLE
Make No and Alt anim notes also effect miss anims

### PR DESCRIPTION
**Pull request by RodneyAnImaginativePerson**

### CODE REVIEW

**Comment by NexIsDumb** [comment]
oh, fair enough

**Comment by RodneyAnImaginativePerson** [comment]
> oh, fair enough

lol

**Comment by NexIsDumb** [comment]
okay this looks good, but for the alt ones, lemme just make a check if the character has the alt anim or otherwhise it wont play anything

**Comment by NexIsDumb** [comment]
okay wait lemme merge this in the meanwhile

**Pull request merged**
