### PR TITLE
Attempt to fix compiling for newer hxvlc versions

### LINKED ISSUE #225: Compiling help: "Too Many Arguments" Error
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet, and make sure you ran the `update.bat` file before building.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
tryin to compile but i get these 2 errors everytime at the end: 
source/funkin/game/cutscenes/VideoCutscene.hx:163: characters 15-24 : Too many arguments
and
source/funkin/game/cutscenes/VideoCutscene.hx:88: characters 15-24 : Too many arguments

### PR DESCRIPTION
**Pull request by MemeHovy**
closes #225 
Note: needs further testing to ensure everything else works, (especially the subtitles thing) but, I tested the first video of Week 7 and it seems to be running fine, I'll do some further testing later, but rn it seems to be working as far as I know

### CODE REVIEW

**Comment by NexIsDumb** [comment]
wait no I know why it happens
the video library is receiving many updates though @NeeEoo is stuck with the older version cause he wants to use that *for now*
i already asked him and he told me to use the commit he was using on that branch instead of making changes about it in the source
done it in #223

**Comment by MemeHovy** [comment]
> wait no I know why it happens the video library is receiving many updates though @NeeEoo is stuck with the older version cause he wants to use that _for now_ i already asked him and he told me to use the commit he was using on that branch instead of making changes about it in the source done it in #223 (tested and ofc there are no more errors)

yes I know about that, that’s why I tried to fix it in the first place, but apparently he doesn't wanna update so I’ll close this for now

**Comment by MemeHovy** [comment]
I’ll leave the branch just in case

**Comment by NexIsDumb** [comment]
alr

**Pull request closed without merging**
