### PR TITLE
Icon bop toggle

### PR DESCRIPTION
**Pull request by usb-port-2**
Basically I tried to change the icon size to 1 on update or postUpdate, but it does this weird shake instead so I thought this would be a nice addition for ease of use

(Bromaster819 said it was a good idea so)

### CODE REVIEW

**Comment by usb-port-2** [comment]
Also I fixed a typo who on the dev team is dyslexic

**Comment by usb-port-2** [comment]
https://cdn.discordapp.com/attachments/1029122193411547178/1251630729138536458/1dc32cba0a72816b.mp4

Here's an example of the weird shake I mentioned

The code I used to set the icon scale was setting both icons scale to 1 on update

**Review by usb-port-2 — COMMENTED** [review]
Disables icon lerping

**Comment by NexIsDumb** [comment]
meh ig its the github preview the one bugged bruh
ty!!

**Comment by NexIsDumb** [comment]
okay nvm??😭

**Pull request merged**
