### PR TITLE
File and folder organization

### PR DESCRIPTION
**Pull request by doggogit**
Hi, first PR here, wanted to do a clean-up, both folder and file wise.

# Changes
* Removed `BETAMESSAGE.md` as I feel it should be highlighted within the patch notes themselves and the extra file isn't necessary. **If people read the patch notes and fuck around with the engine itself, this file isn't needed.**
* The `README` has been shortened down, splitting sections into their own files/extensions in `other/`.
    * Moved `What can you do or not do` into `FEATURES.md`.
    * `How to build` has been moved into a _completely_ new file named `BUILDING.md`.
    * `SECRET REPO INSTRUCTIONS.md` has been moved into `other/` from `art/`.
* Removal of unedited/unwanted .fla files, kept the edited ones in `flashFiles`.
* Put all the teaser layers and image files into one folder called `teasers/`.
* Removed some base game files like `preloaderArt`, `Funkin.bmp`, `c_z.mp3`, etc. since they go unused.
* Removed some of the meme-y files put into the `art/` folder.
* Moved the `libs.xml` file from the root folder to `commandline/`.

If you wish for any files to be returned or if you feel like adjustments can be made, just make a comment or leave a review. I'll be sure to take a look. Cheers.

### CODE REVIEW

**Comment by NeeEoo** [comment]
keep generateDocs.bat since we use a seperate repo where we store the docs since its cleaner that way

**Comment by NeeEoo** [comment]
and im not a fan of the movement of the shell scripts cne and update since ppl might get confused

**Comment by NexIsDumb** [comment]
I would also avoid putting stuff in a docs folder because thats what the docsUpdate.bat needs whenever we have to update the pages repository

**Comment by doggogit** [comment]
> keep generateDocs.bat since we use a seperate repo where we store the docs since its cleaner that way

Will return it, give me a minute

**Comment by doggogit** [comment]
> and im not a fan of the movement of the shell scripts cne and update since ppl might get confused

Should I return them to the root folder or do you have any other ideas?

**Comment by doggogit** [comment]
> I would also avoid putting stuff in a docs folder because thats what the docsUpdate.bat needs whenever we have to update the pages repository

Fair enough, I could rename the folder to something else

**Comment by doggogit** [comment]
I'll wait until you guys decide where the shell scripts need to be, I _personally_ dislike them being in the root folder, cause it's just kinda cluttered, but if you wish to keep it that way, then I'll put em there 👍

**Comment by NexIsDumb** [comment]
sure, we'll for sure tell you
but you'll have to wait a little as we'll look through all the pull requests for good as soon as we finish the new update

**Comment by doggogit** [comment]
> sure, we'll for sure tell you but you'll have to wait a little as we'll look through all the pull requests for good as soon as we finish the new update

Alright, don't mind waiting, take your time

**Comment by NeeEoo** [comment]
i also think this commit will have to be merged after the update is released

**Comment by doggogit** [comment]
> Please make the 2 files have the correct pemissions

Which ones?

**Comment by NeeEoo** [comment]
The 2 shell files

**Comment by NexIsDumb** [comment]
@doggogit remove th commit that i reverted from the guy with the lib changes

**Comment by doggogit** [comment]
> @doggogit remove th commit that i reverted from the guy with the lib changes

How do you remove commits like that... I have no clue

**Comment by NexIsDumb** [comment]
> > @doggogit remove th commit that i reverted from the guy with the lib changes
> 
> 
> 
> How do you remove commits like that... I have no clue

hold on

**Comment by NexIsDumb** [comment]
there ya go
for reverting commits you can just right click a commit in hithub desktop and select revert changes in commit

**Comment by doggogit** [comment]
> there ya go for reverting commits you can just right click a commit in github desktop and select revert changes in commit

Ah, alright, I don't use GitHub Desktop, but good to know 👍

**Comment by NeeEoo** [comment]
Skärmavbild 2024-08-03 kl  18 55 57

Can you move them back?

**Comment by doggogit** [comment]
> Skärmavbild 2024-08-03 kl 18 55 57
> Can you move them back?

Where to?

**Comment by NeeEoo** [comment]
> > Skärmavbild 2024-08-03 kl 18 55 57
> 
> > Can you move them back?
> 
> 
> 
> Where to?

Back to original place

**Comment by doggogit** [comment]
Is this alright?

**Comment by doggogit** [comment]
Due to the amount of commits and changes that have happened, is it okay if this PR gets closed and is re-opened later?

I cba to deal with the merge conflicts...

**Comment by NexIsDumb** [comment]
fine by me and dw we will merge this eventually when the update comes out
which is almost done lmao

**Comment by doggogit** [comment]
> fine by me and dw we will merge this eventually when the update comes out which is almost done lmao

Alrighty

**Pull request closed without merging**
