### PR TITLE
Replace editor blur shaders with OpenFL's BlurFilter + Better blur options

### PR DESCRIPTION
**Pull request by maplesyruppppppp**
apparently there's a blur filter openfl has that looks entirely the same as the shader used for the editors
think of this as a better replacement! (and also a less laggier way to blur the bg)

### CODE REVIEW

**Comment by NexIsDumb** [comment]
okay I think this really looks nice
do u have to change anything else before i merge?

**Comment by maplesyruppppppp** [comment]
> okay I think this really looks nice do u have to change anything else before i merge?

nope !! i believe its completely finished

**Comment by maplesyruppppppp** [comment]
> > okay I think this really looks nice do u have to change anything else before i merge?
> 
> nope !! i believe its completely finished

nvm neeo wants me to add 1 more thing rq lol

**Comment by NexIsDumb** [comment]
oop, alr

**Comment by maplesyruppppppp** [comment]
closing this cuz i completely forgot about it lolll

**Comment by NexIsDumb** [comment]
fair nuff lmfao

**Pull request closed without merging**
