### PR TITLE
Change some strings to comply with the newest version

### PR DESCRIPTION
**Pull request by crowplexus**

### CODE REVIEW

**Comment by crowplexus** [comment]
anything i forgot just comment it here so i can fix it lol

**Comment by NexIsDumb** [comment]
fair enough😭
i'll leave this open for a day or a little bit more if someone notices more parts

**Comment by crowplexus** [comment]
also you can change that final to var in the codename build field if needed

**Comment by NexIsDumb** [comment]
> also you can change that final to var in the codename build field if needed

fair enough, but I think as for now its better if it stays final
if modders are gonna request it, we could change it to var for sure

**Comment by NexIsDumb** [comment]
alr, i think its time to merge this
i might use that final string for other parts in the code for qol, thanks!

**Comment by NexIsDumb** [comment]
oh shit, deleting that main caused problems
imma fix later

**Pull request merged**
