### PR TITLE
ShaderResizeFix fix for cameras

### PR DESCRIPTION
**Pull request by Sword352**
sans undertale

### CODE REVIEW

**Review by NexIsDumb — APPROVED** [review]
sasn undertail

**Review by MemeHovy — APPROVED** [review]

**Comment by Sword352** [comment]
its been 4 months lol

**Comment by NexIsDumb** [comment]
> its been 4 months lol

idk since psych is dying and i just started working on the asynced credits state on codename i just came back to life lmfao

**Comment by Sword352** [comment]
> > its been 4 months lol
> 
> idk since psych is dying and i just started working on the asynced credits state on codename i just came back to life lmfao

aint no way bruv doin multithreaded state

**Comment by NexIsDumb** [comment]
> > > its been 4 months lol
> > 
> > idk since psych is dying and i just started working on the asynced credits state on codename i just came back to life lmfao
> 
> aint no way bruv doin multithreaded state

yasss

**Comment by lunarcleint** [comment]
this did not age well

**Comment by Sword352** [comment]
sob

**Pull request closed without merging**
