### PR TITLE
GIF Support (flxgif)

### PR DESCRIPTION
**Pull request by NotSynthic**

### CODE REVIEW

**Comment by NeeEoo** [comment]
Why not like extract your gif into a spritesheet? gifs are pretty slow

**Comment by taufei** [comment]
> Why not like extract your gif into a spritesheet? gifs are pretty slow

Honestly yeah i can see that but honestly gif support would be funny as fuck

**Comment by NotSynthic** [comment]
> Why not like extract your gif into a spritesheet? gifs are pretty slow

**Comment by NotSynthic** [comment]
its easier to setup ig

**Comment by NeeEoo** [comment]
Having a feature just because its fun, is just gonna lead to bloat

**Comment by NotSynthic** [comment]
ight bro

**Comment by lunarcleint** [comment]
sorry but gif support is just not needed currently 😭, thank you for spending your time contributing for the engine tho :D

**Pull request closed without merging**
